// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FilepondController from "./filepond_controller"
application.register("filepond", FilepondController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ToastifyController from "./toastify_controller"
application.register("toastify", ToastifyController)
